services:
  - type: web
    name: food-ordering-system-1
    env: python
    buildCommand: "./render-build.sh"
    startCommand: "gunicorn streetfood.wsgi:application"
    plan: free
    autoDeploy: true

