services:
  - type: web
    name: streetfood
    env: python
    buildCommand: "./render-build.sh"
    startCommand: "gunicorn streetfood.wsgi:application"
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
